# These are supported funding model platforms

github: ['luke-hill']
patreon: # Replace with a single Patreon username
open_collective: site-prism
ko_fi: # Replace with a single Ko-fi username
tidelift: rubygems/site_prism
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
