inherit_from: .rubocop_todo.yml

# This allows us to merge arrays for Exclude rules on AllCops or a specific cop
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

# We don't use MFA yet
Gemspec/RequireMFA:
  Enabled: false

# This allows a longer LineLength and ignores cuke definitions
Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - '^Given'
    - '^When'
    - '^Then'

# Our gemspec and Spec files contain huge blocks and need to
Metrics/BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

# We are a DSL, so we occasionally need to use `.set_` prefixes on our DSL names
Naming/AccessorMethodName:
  Enabled: false

# Stylistic preference to make the RSpec tests flow better
RSpec/MessageSpies:
  EnforcedStyle: receive

# We don't need to document any testing code
Style/Documentation:
  Exclude:
    - features/**/*

# This is a better style, and should be the default IMO
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
