# This allows us to merge arrays for Exclude rules on AllCops or a specific cop
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# Document gem dependencies in the gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Don't use MFA
Gemspec/RequireMFA:
  Enabled: false

# This allows a longer LineLength and ignores cuke definitions
Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - ^Given
    - ^When
    - ^Then

# These scenarios need empty blocks to trigger an error for not permitting blocks
Lint/EmptyBlock:
  Exclude:
    - spec/site_prism/element_spec.rb
    - spec/site_prism/elements_spec.rb

# Don't count long arrays/hashes/heredocs as long methods
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']

# We are a DSL, so we occasionally need to use `.set_` prefixes on our DSL names
Naming/AccessorMethodName:
  Enabled: false

# This is a single standardised transform
RSpec/SpecFilePathFormat:
  CustomTransform:
    RSpecMatchers: rspec_matchers

# This is a single standardised transform - DEPRECATED (Remove in rubocop-rspec v3)
RSpec/FilePath:
  CustomTransform:
    RSpecMatchers: rspec_matchers

# Stylistic preference
RSpec/MessageSpies:
  EnforcedStyle: receive

# Test the RSpec matcher is correctly calling the `has_no` method
RSpec/MultipleExpectations:
  Exclude:
    - spec/site_prism/element_spec.rb

# Don't document any testing code
Style/Documentation:
  Exclude:
    - features/**/*

# Stylistic preference
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# False negative: https://github.com/rubocop/rubocop/issues/12423
Style/YodaCondition:
  Exclude:
    - lib/site_prism/dsl/locators.rb
