inherit_from: .rubocop_todo.yml

# This allows us to merge arrays for Exclude rules on AllCops or a specific cop
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# We don't use MFA yet
Gemspec/RequireMFA:
  Enabled: false

# This allows a longer LineLength and ignores cuke definitions
Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - ^Given
    - ^When
    - ^Then

# We are a DSL, so we occasionally need to use `.set_` prefixes on our DSL names
Naming/AccessorMethodName:
  Enabled: false

# This will be present until v5 beta
Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'lib/site_prism/page.rb'

# Stylistic preference to make the RSpec tests flow better
RSpec/MessageSpies:
  EnforcedStyle: receive

# We need to test the RSpec matcher is correctly calling the has_no method
RSpec/MultipleExpectations:
  Exclude:
    - spec/site_prism/element_spec.rb

# We don't need to document any testing code
Style/Documentation:
  Exclude:
    - features/**/*

# This is a better style, and should be the default IMO
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
